"""
Builds frontend/icons.css (2026-10-04) - replaces the Tabler icon FONT.

The site loaded the whole Tabler webfont (452KB woff2 + 36KB CSS, ~5,000 icons,
from a third-party host) on every page to draw 13 icons. This draws only those
13 as inline SVG shapes used as CSS masks, written into frontend/site.css
between the ICONS markers (and mirrored to docs/site.css), so there is no icon
download at all and the icons still take the text colour and font size:

    <i class="ti ti-search"></i>      (markup is unchanged)

ADD AN ICON: add its Tabler name to ICONS below, run this script (needs network
once, to fetch that icon's SVG from the same Tabler release), commit icons.css and the
re-stamped pages.
ALIASES maps a name the code uses to a different drawing (ti-vase does not exist
in Tabler, so it was blank; it now draws the bottle).

    python3 build_icon_css.py
"""

import re
import shutil
import urllib.parse
from pathlib import Path

import requests

TABLER_VERSION = "3.46.0"
ICONS = ["armchair", "arrow-right", "arrow-up-right", "arrows-shuffle", "bulb", "external-link",
         "info-circle", "photo", "search", "share-2", "table", "tag", "bottle", "chevron-down"]
ALIASES = {"vase": "bottle"}

ROOT = Path(__file__).parent.parent
ICONS_CSS = ROOT / "frontend" / "icons.css"
HEADER = "/* Generated by scraper/build_icon_css.py - do not edit by hand. */\n"

BASE = """.ti {
  display: inline-block; width: 1em; height: 1em; flex-shrink: 0;
  vertical-align: -0.125em; line-height: 1; font-style: normal;
  background-color: currentColor;
  -webkit-mask: var(--ti) center / contain no-repeat; mask: var(--ti) center / contain no-repeat;
}"""


def fetch_svg(name):
    url = f"https://cdn.jsdelivr.net/npm/@tabler/icons@{TABLER_VERSION}/icons/outline/{name}.svg"
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    return r.text


def to_mask_uri(svg):
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    inner = re.sub(r'<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*/>', "", inner)  # the empty bounding box
    inner = re.sub(r"\s+", " ", inner).strip().replace('"', "'")
    body = (
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='#000' "
        "stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>" + inner + "</svg>"
    )
    return "url(\"data:image/svg+xml," + urllib.parse.quote(body, safe="/:=' ,.-").replace(" ", "%20") + "\")"


def build():
    rules = [BASE]
    for name in ICONS:
        rules.append(f".ti-{name} {{ --ti: {to_mask_uri(fetch_svg(name))}; }}")
    for alias, target in ALIASES.items():
        rules.append(f".ti-{alias} {{ --ti: var(--ti-{target}); }}")  # replaced below
    css = "\n".join(rules)
    # aliases need the actual value, not a var() to another rule - inline it
    for alias, target in ALIASES.items():
        value = re.search(rf"\.ti-{re.escape(target)} \{{ --ti: (.*); \}}", css).group(1)
        css = css.replace(f"--ti: var(--ti-{target});", f"--ti: {value};")
    return HEADER + css + "\n"


def main():
    css = build()
    ICONS_CSS.write_text(css)
    shutil.copy(ICONS_CSS, ROOT / "docs" / "icons.css")
    import importlib
    import site_assets
    importlib.reload(site_assets)  # pick up the new content hash
    n = site_assets.stamp_html()
    print(f"wrote {len(ICONS)} icons (+{len(ALIASES)} alias) to icons.css ({len(css)//1024 or 1}KB); stamped {n} pages with {site_assets.ICONS_CSS}")


if __name__ == "__main__":
    main()
